### ISSUE TITLE
Enable multi-platform build

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/gh-action-build-docker-image#1]
If we ever want to build for raspberry PI or any other non amd64 based platform, we should enable `buildx`.

One way to achieve this would be by using the following workflow:
```
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: |
            user/app:latest
            user/app:1.0.0
```

Alternatively, instead of using the `docker/build-push-action`, we can do the same via `docker buildx build --platform ...`.
